id: I959197BA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T23:02:45+00:00'
last_modified: '2022-06-09T04:36:31.801535+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6330
  title: བོད་ཀྱི་དེང་རབས་རྩོམ་རིག་ཞིབ་འཇུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    65BE:
      image_group_id: I1KG6336
      title: Volume 1 of bod kyi deng rabs rtsom rig zhib 'jug
      total_pages: 394
      order: 1
      base_file: 65BE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
