id: P008115
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6330
  title: བོད་ཀྱི་དེང་རབས་རྩོམ་རིག་ཞིབ་འཇུག
  author: ''
  volumes:
    5ceb81b8769d4a7cbf452faa007cbc23:
      image_group_id: I1KG6336
      title: ''
      volume_number: 1
      total_pages: 394
ebook_metadata:
  title: བོད་ཀྱི་དེང་རབས་རྩོམ་རིག་ཞིབ་འཇུག
  author: ''
  sku: P008115
  cover: cover.jpg
  layers:
  - pagination
