id: P008115
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG6330
  title: བོད་ཀྱི་དེང་རབས་རྩོམ་རིག་ཞིབ་འཇུག
  author: ''
  volumes:
    b2688738272a48bdaaf999c52a7f523f:
      image_group_id: I1KG6336
      title: Volume 1 of bod kyi deng rabs rtsom rig zhib 'jug
      volume_number: 1
      total_pages: 394
      base_file: v001.txt
